//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shorty
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLORDERINFO
    {
        public int ORDERID { get; set; }
        public string ORDERNAME { get; set; }
        public Nullable<int> ORDERPRICE { get; set; }
        public string ORDERBARCODE { get; set; }
    }
}
